version: '3.8'

x-db-variables: &db-variables
  POSTGRES_USER: ${POSTGRES_USER-postgres}
  POSTGRES_DB: ${POSTGRES_DB-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}

x-app-variables: &app-variables
  SECRET_KEY: ${SECRET_KEY-my secret key}
  DB_NAME: ${POSTGRES_NAME-postgres}
  DB_HOST: ${POSTGRES_HOST-db}
  DB_PASSWORD: ${POSTGRES_PASSWORD-postgres}  
  DB_USER: ${POSTGRES_USER-postgres}
  DB_PORT: ${POSTGRES_PORT-5432}  

services:
  app:
    restart: always
    image: score-sphere-app
    build:
      context: .
      target: prod

    ports:
      - "8080:8080"

    environment:
      <<: *app-variables
      QUART_AUTH_COOKIE_SECURE: "False"
    
    profiles:
      - full

    depends_on:
      db:
        condition: service_healthy

  db-setup:
    image: score-sphere-app
    environment:
      <<: *app-variables
    profiles:
      - full
    depends_on:
      db:
        condition: service_healthy

    command: sh -c "/venv/bin/aerich upgrade"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db-variables
      PGUSER: postgres

    profiles:
      - full

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis/redis-stack
    volumes:
      - redis-data:/data

    profiles:
      - full

volumes:
  postgres-data:
  redis-data:
